---
- name: Install cjson
  hosts: workers
  become: yes  # 使用root权限执行
  gather_facts: no  # 不收集主机信息
  vars_files:
    - ../shared_vars.yaml
  tasks:
    - name: Install cjson
      shell: "make ; sudo make install"
      args:
        chdir: "{{ base_dir }}/deps/cjson/cJSON"